[package]
name = "multiagent"
version = "0.1.0"
authors = ["Alex Rozgo <alex.rozgo@gmail.com>"]

[dependencies]

[lib]
name = "multiagent"
path = "src/lib.rs"

[[bin]]
name = "multiagent"
path = "src/bin.rs"
